### ISSUE TITLE
License agreement ?

### ISSUE THREAD

**Issue by suryaambrose** [ros-naoqi/nao_meshes_installer#1]
Hey, I just downloaded those meshes installer and I never had any license agreement to click on. 
Is that normal ?

**Comment by mikaelarguedas** [comment]
surprising, did you install the debian package or from github ?
If you install the debian package:
Be aware that is you already installed the debian package before (and accepted the licence agreement) you won't be prompted the licence agreement anymore. Even if you removed the package, as long as you did not purge your apt cache the licence is still considered as accepted. This allow users not to have this licence agreement popping each time they upgrade their system.

ERRATUM: I tried downloading this installer from github and was indeed not prompted any licence agreement to click on. I'll look into it and keep you updated. 
@vrabaud maybe be you know something about this ?

**Comment by mikaelarguedas** [comment]
ok should be fixed for naomeshes-0.6.7-linux-x64-installer.run in fb1f7719bca1d7e420252196cb40ba76f9685dd7
@suryaambrose can you test it and confirm that the file is showing up during the install process ?
If confirmed I'll generate a 32bits installer and remove the unused/outdated previous versions if it's ok with everybody

**Comment by suryaambrose** [comment]
I ran the installer in the github repo. But as you fixed the bug I guess you already found out the problem ^^. 
Just pulled and tried, the license pops out, so it seems fixed good job !
